plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.hw.dpf.information'
    compileSdk 34

    defaultConfig {
        applicationId "com.hw.dpf.information"
        minSdk 10
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation libs.junit
}